K: 11
# K_normal_estimation: 10
epsilon: 0.1
# K=29, eps=0.3 works pretty good for angles

K_2: 11
epsilon_2: 0.1

abs_path: "/home/honzuna/"
# file_name: "pointcloud.pcd"
file_name: "sphere.pcd"

# abs_path: "/home/honzuna/moje/bakalarka/modely/naki_gazebo_resources-master/models/"
# file_name: "cholina/pcd/cholina.pcd"  # 873 273
# file_name: "kn_backyard/pcd/kn_backyard.pcd"  # 4 511 074
# file_name: "kn_gym_A1/pcd/kn_gym_A1.pcd"  # 233 223
# file_name: "koprivna/pcd/koprivna.pcd"  # 411 077

# file_name: "novy_malin/pcd/novy_malin.pcd"  # 653 652
# file_name: "olomouc_marie_snezna/pcd/olomouc_marie_snezna.pcd"  # 3 603 056
# file_name: "olomouc_sv_moric/pcd/olomouc_sv_moric.pcd"  # 1 000 000
# file_name: "prostejov/pcd/prostejov.pcd"  # 2 105 238
# file_name: "smockovi/pcd/smockovi_court.pcd"  # 82 548
# file_name: "stara_voda/pcd/stara_voda.pcd"  # 778 085
# file_name: "sumperk/pcd/sumperk.pcd"  # 548 000
# file_name: "uherske_hradiste/pcd/uherske_hradiste.pcd"  # 2 580 696
# file_name: "zabreh/pcd/zabreh.pcd"  # 1 954 927

trashold: 0.3
k_angle: 0.33
k_halfdisc: 0.33
k_shape: 0.33

weight_boundary: 1.8

q: 0

# RANSAC parameters

n_ransac: 3
k_ransac: 1000
t_ransac: 0.05
# t_ransac: 0.1
d_ransac: 1

uav_min_distance: 0.01
uav_max_distance: 0.1
uav_min_angle: 30
uav_min_area_width: 0.005

